[project]
name = "fyskemqc"
version = "2024.1"
description = "Automatisk metadatakontroll av olika datatyper"
authors = [
    { name = "Jonatan Skogsfors", email = "jonatan.skogsfors@smhi.se" },
    { name = "Ylva Ericson", email = "ylva.ericson@smhi.se" },
    { name = "Lena Viktorsson", email = "lena.viktorsson@smhi.se" }
]
dependencies = [
    "pandas>=1.5.0",
]
requires-python = ">=3.8"
readme = "README.md"
license = { file = "LICENSE" }

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=8.1.1",
    "ruff>=0.3.4",
    "pre-commit>=3.5.0",
]

[tool.ruff]
line-length = 90
indent-width = 4
target-version = "py38"

[tool.ruff.lint]
select = ["F", "E", "W", "I001"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"